spring:
  cloud:
    gateway:
      routes:
        - id: java_rote
          uri: https://github.com/prometheus/prometheus/releases/tag/v2.17.0-rc.4
          predicates :
            - Path= /get
      discovery:
        locator:
          enabled: true  #开启自动化代理
  application:
    name: gateeway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug